---
  title: "Lecture Slides - Quantitative Methods" 
  site: distill::distill_website

---



```{r ,echo=FALSE, message=FALSE}

fileo=list.files(path="../slides",pattern="^Topic")
filei=list.files(path="../slides",pattern="CCMF")

file=c(filei,fileo)

#path="https://github.com/mondpanther/datastorieshub/raw/master/slides/"
path="https://mondpanther.github.io/datastorieshub/slides/"
full=paste0(path,file[[1]])


```

```{r echo = FALSE, results = "asis"}

for (i in seq(1,length(file))) {
  
  full=paste0(path,file[[i]])
  cur=paste("- [", file[[i]],"](",full,") \n")
  cat(cur)

}
```



# R scripts


```{r ,echo=FALSE, message=FALSE}

fileo=list.files(path="./code",pattern="^Topic")
filei=list.files(path="./code",pattern="^Farage")

file=c(filei,fileo)

#path="https://github.com/mondpanther/datastorieshub/raw/master/slides/"
path="https://mondpanther.github.io/datastorieshub/code/"
full=paste0(path,file[[1]])


```

```{r echo = FALSE, results = "asis"}

for (i in seq(1,length(file))) {
  
  full=paste0(path,file[[i]])
  cur=paste("- [", file[[i]],"](",full,") \n")
  cat(cur)

}
```


# Guides

```{r ,echo=FALSE, message=FALSE}

file=list.files(path="./code",pattern="Guide")
#filei=list.files(path="./code",pattern="^Farage")

#file=c(filei,fileo)

#path="https://github.com/mondpanther/datastorieshub/raw/master/slides/"
path="https://mondpanther.github.io/datastorieshub/code/"
full=paste0(path,file[[1]])


```

```{r echo = FALSE, results = "asis"}

for (i in seq(1,length(file))) {
  
  full=paste0(path,file[[i]])
  cur=paste("- [", file[[i]],"](",full,") \n")
  cat(cur)

}
```




