---
title: "Covid and vaxxination"
output: html_notebook
---




# Load data

```{r}


df=read.csv("https://covid.ourworldindata.org/data/owid-covid-data.csv")
names(df)


library(fixest)
library(lubridate)

```



# Prepare data

Aggregate to month; i.e. we wanna analyse this at the country and month level

```{r}

dfm = df %>% mutate(month=substr(date, 1, 7)   # Create month by taking the first 7 characters of the date string
                    ) %>%     
         group_by(month,iso_code) %>%           # Define groups by month and country
         filter(date==max(date)) %>%            # Take only the last day of every month
         select(iso_code,                       # Select only some variables...
                date,
                location,
                starts_with("total_"),
                population,
                population_density,continent)

dfm=dfm %>% filter(substr(iso_code, 1, 4)!="OWID")  # We get rid of observations that refer to groups of countries (i.e. those that have an OWID identifier)



# Replace the missing values with 0
# but only at the beginning because at the end that just means missing values...
library(tidyr)  #  this package gives us the replace_na() command

dfm=dfm %>% arrange(iso_code,date) %>% 
    group_by(iso_code) %>% 
    mutate( across( starts_with("total_"), ~ifelse( is.na(.x) & cumsum( replace_na(.x, 0) )==0 ,0,.x)))


dfm=dfm %>% filter(as_date("2021-10-30")>date)
write.csv(dfm,"dfm.csv")




dfm=dfm %>% mutate(date=as_date(date))

```



Clean up a bit more

```{r}





dfm=dfm %>% arrange(iso_code,date) %>% 
  group_by(iso_code) %>% mutate(L1vax=dplyr::lag(total_vaccinations_per_hundred),
                                vax=total_vaccinations_per_hundred,
                                lndeaths=log(1+total_deaths_per_million),
                                deaths=total_deaths_per_million,
                                lnvax=log(1+vax))



```


## A cross section?


Let's compare 

```{r}

cross=dfm %>% group_by(iso_code) %>% 
  filter(!is.na(vax) & !is.na(deaths)) %>% filter(month=="2021-02" | month==max(month)) %>% 
  arrange(iso_code,date) %>% group_by(iso_code) %>% 
  mutate(period=1:n())


write.csv(cross,"cross.csv")



```


```{r}

cross=cross %>% arrange(iso_code,date) %>% 
  group_by(iso_code) %>% 
  mutate(Ddeaths=deaths-dplyr::lag(deaths)) %>% 
  
  mutate(across( c("deaths","vax","lndeaths","lnvax"),
                                        ~.x-dplyr::lag(.x),
                                        .names="D{.col}"))
                                
                                
    

library(ggplot2)

cross %>% ggplot(aes(x=Dvax,  y=Ddeaths, color=continent)) +geom_point()+geom_smooth(method="lm",se=F)+theme_minimal()



cross %>% ggplot(aes(x=Dvax,  y=Dlndeaths, color=continent,label=location))+
          geom_point()+geom_smooth(method="lm",se=F)+theme_minimal()+
          geom_text(size=3,check_overlap = TRUE)


```


Let's only look at Europe
```{r}
cross_eur=cross %>% filter(continent=="Europe") 



cross_eur %>% ggplot(aes(x=vax,  y=deaths, color=continent,label=location))+
          geom_point()+geom_smooth(method="lm",se=F)+theme_minimal()+
          geom_text(size=3)


cross_eur %>% ggplot(aes(x=vax,  y=Ddeaths, color=continent,label=location))+
          geom_point()+geom_smooth(method="lm",se=F)+theme_minimal()+
          geom_text(size=3)



cross %>% ggplot(aes(x=vax,  y=Dlndeaths, color=continent,label=location))+
          geom_point()+geom_smooth(method="lm",se=F)+theme_minimal()+
          geom_text(size=3,check_overlap = TRUE)



cross %>% ggplot(aes(x=Dlnvax,y=Dlndeaths)) +geom_point()+geom_smooth(method="lm")


cross %>% ggplot(aes(x=Dvax,y=Ddeaths)) +geom_point()+geom_smooth(method="lm")

```




A first regression


```{r}



r1=feols(total_deaths_per_million~total_vaccinations_per_hundred+L1vax+total_tests_per_thousand|iso_code+month,dfm)
r1 %>% summary()



r1=feols(lndeathsPc~total_vaccinations_per_hundred+L1vax+total_tests_per_thousand|iso_code+month,dfm)
r1 %>% summary()



r1=feols(lndeathsPc~lnvaxPc|iso_code+month,dfm)
r1 %>% summary()








r1=feols(total_deaths_per_million~vax+L1vax|iso_code+month,dfm %>% filter(continent=="Europe"))
r1 %>% summary()


r1=feols(total_deaths_per_million~L1vax|iso_code+month,dfm %>% filter(continent!="Asia"))
r1 %>% summary()



r1=fepois(total_deaths_per_million~vax+L1vax|iso_code+month,dfm)
r1 %>% summary()


r1=fepois(total_deaths_per_million~vax+L1vax|iso_code+month,dfm %>% filter(continent=="Europe"))
r1 %>% summary()





r1=fepois(total_deaths_per_million~total_vaccinations_per_hundred|iso_code+month,dfm)
r1 %>% summary()



r1=feols(total_cases_per_million~total_vaccinations_per_hundred+total_tests_per_thousand|iso_code+month,dfm)
r1 %>% summary()


```
